spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/external_api_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: user
    password: user1234

  jpa:
    hibernate:
      ddl-auto: update # 테이블 자동 생성/수정
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  pattern:
    console: "[%d{yyyy-mm-dd HH:mm:ss}] [%x{traceId}] %-5level - %msg%n"
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  port: 38080

riot:
  api:
    url: https://asia.api.riotgames.com
    key: ${RIOT_API_KEY}
    champ: http://ddragon.leagueoflegends.com/cdn/14.5.1/data/ko_KR/champion.json